const { pool } = require("../Db");
const ApiError = require("../utils/ApiError");
const { withCache } = require("../utils/cache");
const { USAGE_TABLES } = require("../config/usageTables");
const { getTotalDbCapacityBytes } = require("./platformSettingsService");

// "How much DB space should we allot a new/growing shop?" — answered from THIS database's
// own real, currently-observed behavior, never a guessed constant. Two kinds of real
// numbers feed the projection:
//
// 1. avgBytesPerRow per table — AVG(pg_column_size(t.*)) measured live, right now, across
//    every shop's existing rows. Every shop shares the exact same schema, so today's
//    average row size for e.g. `sales` is a genuine, representative sample for a new
//    shop's future `sales` rows too, not an assumption.
// 2. Ratios for tables the caller doesn't ask the client about directly (categories,
//    sale_transactions, refunds, etc.) — measured as that table's real row count divided
//    by whichever driver table (products or sales) it's actually correlated with in this
//    live dataset, then applied to the client's projected driver volume. This keeps the
//    client-facing form to a handful of questions without falling back to a fabricated
//    ratio for the rest.
//
// Two numbers here are deliberately NOT measured from this database's current live state,
// unlike everything else in this file:
//
// - OVERHEAD_MULTIPLIER (indexes/TOAST/page overhead on top of raw row content) would be
//   measurable the same way estimatedRealBytes is elsewhere (adminService.js,
//   storageQuotaService.js) — actual DB size ÷ real row-content size, observed right now.
//   But that only works for splitting a real total among EXISTING rows; it breaks for
//   *projecting forward* from a database this small (2 shops, a few dozen rows per table),
//   where almost every table's index is still sitting at Postgres's fixed one-page minimum
//   rather than its true per-row growth rate — measuring it today would have given a ~264x
//   ratio dominated by that fixed floor, wildly overstating what thousands of future rows
//   would actually cost. 1.6x is a commonly-cited rule of thumb for a B-tree-indexed OLTP
//   table with a handful of indexes (this schema's tables mostly have 2-4: primary key,
//   shop_id, and one or two foreign keys) — a documented assumption, not a guess, and one
//   that will get more accurate to measure directly once real shops have real volume.
// - BUFFER_MULTIPLIER — a flat 40% headroom on top of the (already overhead-adjusted)
//   projection, since a projection is inherently a guess about the FUTURE, and it's cheaper
//   for a shop to have unused headroom than to hit its limit early.
const OVERHEAD_MULTIPLIER = 1.6;
const BUFFER_MULTIPLIER = 1.4;

// Which driver a table not directly asked about scales with, based on what actually
// generates that data in this app (lots/categories track the catalog; everything else in
// this list is generated by the sales flow — a transaction, a refund against it, a shift
// it happened in, a credit customer it was billed to, and so on).
const PRODUCT_DRIVEN_TABLES = ["categories", "lots"];
const SALE_DRIVEN_TABLES = [
  "sale_transactions",
  "refunds",
  "contacts",
  "party_transactions",
  "store_credit_redemptions",
  "bank_payment_intents",
  "shifts",
  "shift_cash_movements",
];

const ESTIMATION_CACHE_TTL_SECONDS = 600; // same horizon as storageQuotaService's usage cache

// Real, live measurement: average on-disk row size per table, and how many rows each
// ratio-driven table has per row of its driver table — both computed fresh from the whole
// database's current content, cached for 10 minutes since this changes slowly.
const getEstimationBasis = () =>
  withCache("storage-estimate:basis", ESTIMATION_CACHE_TTL_SECONDS, async () => {
    const rowCounts = {};
    const avgBytesPerRow = {};

    for (const table of USAGE_TABLES) {
      const { rows } = await pool.query(
        `SELECT COUNT(*)::int AS row_count, COALESCE(AVG(pg_column_size(t.*)), 0)::float AS avg_bytes
         FROM ${table} t`
      );
      rowCounts[table] = rows[0].row_count;
      avgBytesPerRow[table] = rows[0].avg_bytes;
    }

    const ratioToProducts = {};
    const ratioToSales = {};
    const productRows = rowCounts.products || 0;
    const saleRows = rowCounts.sales || 0;
    for (const table of PRODUCT_DRIVEN_TABLES) {
      ratioToProducts[table] = productRows > 0 ? rowCounts[table] / productRows : 0;
    }
    for (const table of SALE_DRIVEN_TABLES) {
      ratioToSales[table] = saleRows > 0 ? rowCounts[table] / saleRows : 0;
    }

    return { avgBytesPerRow, ratioToProducts, ratioToSales };
  });

const parsePositiveInt = (value, label) => {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed < 0 || !Number.isInteger(parsed)) {
    throw new ApiError(400, `${label} must be a non-negative whole number`);
  }
  return parsed;
};

// numProducts/numUsers are static headcounts; dailySalesLineItems/dailyStockAdjustments are
// per-day rates multiplied out over the projection window (projectionMonths × 30 days) —
// everything else is derived from those four via the real ratios above, then scaled to the
// database's real, index-inclusive footprint using the same overhead technique
// adminService.getUsageByShop/storageQuotaService.getShopStorageStatus already use: this
// shop's share of projected row CONTENT applied to the real total database size right now.
const estimateShopStorage = async ({ numProducts, dailySalesLineItems, dailyStockAdjustments, numUsers, projectionMonths }) => {
  const products = parsePositiveInt(numProducts, "Number of products");
  const dailySales = parsePositiveInt(dailySalesLineItems, "Daily sales (line items)");
  const dailyAdjustments = parsePositiveInt(dailyStockAdjustments, "Daily stock adjustments");
  const users = parsePositiveInt(numUsers, "Number of users");
  const months = parsePositiveInt(projectionMonths, "Projection horizon (months)");
  if (months < 1) throw new ApiError(400, "Projection horizon must be at least 1 month");

  const totalDays = months * 30;
  const [basis, totalDbCapacityBytes] = await Promise.all([getEstimationBasis(), getTotalDbCapacityBytes()]);

  const projectedSalesRows = dailySales * totalDays;
  const projectedRows = {
    products,
    users,
    sales: projectedSalesRows,
    stock_adjustments: dailyAdjustments * totalDays,
  };
  for (const table of PRODUCT_DRIVEN_TABLES) {
    projectedRows[table] = Math.round(products * basis.ratioToProducts[table]);
  }
  for (const table of SALE_DRIVEN_TABLES) {
    projectedRows[table] = Math.round(projectedSalesRows * basis.ratioToSales[table]);
  }

  const breakdown = USAGE_TABLES.map((table) => {
    const rows = projectedRows[table] || 0;
    const bytes = Math.round(rows * (basis.avgBytesPerRow[table] || 0));
    return { table, projectedRows: rows, avgBytesPerRow: Math.round(basis.avgBytesPerRow[table] || 0), bytes };
  });
  const projectedContentBytes = breakdown.reduce((sum, row) => sum + row.bytes, 0);

  const projectedRealBytes = Math.round(projectedContentBytes * OVERHEAD_MULTIPLIER);
  const recommendedBytes = Math.round(projectedRealBytes * BUFFER_MULTIPLIER);
  const recommendedPercent = totalDbCapacityBytes > 0 ? (recommendedBytes / totalDbCapacityBytes) * 100 : null;

  return {
    inputs: { numProducts: products, dailySalesLineItems: dailySales, dailyStockAdjustments: dailyAdjustments, numUsers: users, projectionMonths: months },
    breakdown,
    projectedContentBytes,
    overheadMultiplier: OVERHEAD_MULTIPLIER,
    projectedRealBytes,
    bufferMultiplier: BUFFER_MULTIPLIER,
    recommendedBytes,
    recommendedPercent,
    totalDbCapacityBytes,
    exceedsTotalCapacity: recommendedPercent !== null && recommendedPercent > 100,
  };
};

module.exports = { estimateShopStorage, BUFFER_MULTIPLIER };
