// Writes device/schema.sql: the cloud database's current schema (tables, sequences,
// constraints, indexes, views), as the device's local database needs it.
//
//   node scripts/export-schema.js
//
// Read-only against the cloud. The cloud's migrations are the source of truth; this snapshots
// what they produced, so the device never has to replay 31 migrations written for Supabase.
// Left out on purpose: row-level security (policies, the pos_app role, app_shop_id()) — a
// device's database only ever holds one shop — and Supabase's own schemas and extensions.
const fs = require("fs");
const path = require("path");
const { systemPool: db } = require("../../ExpressBackend/Db");

// Extensions the schema's indexes use that PGlite ships (see localDb.js).
const EXTENSIONS = ["pg_trgm", "btree_gin"];
// The cloud's own record of devices and their sync — never part of a device's database.
const CLOUD_ONLY = ["devices", "sync_log", "sync_rejections", "sync_changes"];
// The newest cloud migration this export includes: localDb.js marks every device migration up
// to it as already applied when it creates a database from this file.
const MIGRATIONS_DIR = path.join(__dirname, "..", "..", "ExpressBackend", "migrations");
const latestMigration = () => Math.max(...fs.readdirSync(MIGRATIONS_DIR).map((f) => parseInt(f, 10)).filter(Number.isFinite));

const q = async (sql, params) => (await db.query(sql, params)).rows;
const ident = (name) => (/^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name.replace(/"/g, '""')}"`);

(async () => {
  const out = [
    "-- Generated by device/scripts/export-schema.js from the cloud database. Do not edit by hand.",
    `-- ${new Date().toISOString()}`,
    `-- cloud-migrations: ${latestMigration()}`,
    "",
    ...EXTENSIONS.map((e) => `CREATE EXTENSION IF NOT EXISTS ${e};`),
    "",
  ];

  const sequences = await q(
    `SELECT s.sequencename, s.data_type::text, s.start_value, s.increment_by FROM pg_sequences s
     WHERE s.schemaname = 'public' AND NOT EXISTS (
       SELECT 1 FROM pg_depend d JOIN pg_class seq ON seq.oid = d.objid JOIN pg_class t ON t.oid = d.refobjid
       WHERE seq.relname = s.sequencename AND d.deptype IN ('a', 'i') AND t.relname = ANY($1))
     ORDER BY s.sequencename`,
    [CLOUD_ONLY]
  );
  for (const s of sequences) {
    out.push(`CREATE SEQUENCE ${ident(s.sequencename)} AS ${s.data_type} START ${s.start_value} INCREMENT ${s.increment_by};`);
  }
  out.push("");

  const tables = (
    await q(`SELECT c.oid, c.relname FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
             WHERE n.nspname = 'public' AND c.relkind = 'r' AND NOT (c.relname = ANY($1)) ORDER BY c.relname`, [CLOUD_ONLY])
  );
  for (const t of tables) {
    const columns = await q(
      `SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS type, a.attnotnull,
              pg_get_expr(d.adbin, d.adrelid) AS def, a.attidentity, a.attgenerated
       FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
       WHERE a.attrelid = $1 AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`,
      [t.oid]
    );
    const lines = columns.map((c) => {
      let line = `  ${ident(c.attname)} ${c.type}`;
      if (c.attidentity) line += ` GENERATED ${c.attidentity === "a" ? "ALWAYS" : "BY DEFAULT"} AS IDENTITY`;
      else if (c.attgenerated) line += ` GENERATED ALWAYS AS (${c.def}) STORED`;
      else if (c.def) line += ` DEFAULT ${c.def}`;
      if (c.attnotnull) line += " NOT NULL";
      return line;
    });
    out.push(`CREATE TABLE ${ident(t.relname)} (\n${lines.join(",\n")}\n);`);
  }
  out.push("");

  // Primary keys, uniques and checks first (foreign keys need the uniques they point at).
  const constraints = await q(
    `SELECT c.conrelid::regclass::text AS tbl, c.conname, c.contype, pg_get_constraintdef(c.oid) AS def
     FROM pg_constraint c JOIN pg_namespace n ON n.oid = c.connamespace
     WHERE n.nspname = 'public' AND c.contype IN ('p', 'u', 'c', 'x', 'f') AND c.conrelid <> 0
       AND NOT (c.conrelid::regclass::text = ANY($1))
     ORDER BY CASE c.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'x' THEN 2 WHEN 'c' THEN 3 ELSE 4 END, 1, 2`,
    [CLOUD_ONLY]
  );
  for (const c of constraints) out.push(`ALTER TABLE ${c.tbl} ADD CONSTRAINT ${ident(c.conname)} ${c.def};`);
  out.push("");

  for (const s of await q(
    `SELECT s.relname AS seq, t.relname AS tbl, a.attname AS col
     FROM pg_depend d JOIN pg_class s ON s.oid = d.objid AND s.relkind = 'S'
     JOIN pg_class t ON t.oid = d.refobjid JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
     JOIN pg_namespace n ON n.oid = s.relnamespace
     WHERE n.nspname = 'public' AND d.deptype IN ('a', 'i') AND NOT (t.relname = ANY($1))`,
    [CLOUD_ONLY]
  )) {
    out.push(`ALTER SEQUENCE ${ident(s.seq)} OWNED BY ${ident(s.tbl)}.${ident(s.col)};`);
  }
  out.push("");

  // Indexes that aren't already a constraint's own index.
  const indexes = await q(
    `SELECT pg_get_indexdef(i.indexrelid) AS def
     FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conindid = i.indexrelid)
       AND NOT (i.indrelid::regclass::text = ANY($1))
     ORDER BY c.relname`,
    [CLOUD_ONLY]
  );
  for (const i of indexes) out.push(`${i.def.replace(/public\./g, "")};`);
  out.push("");

  // Views, each after the views it reads from.
  const views = await q(
    `SELECT c.oid, c.relname, pg_get_viewdef(c.oid, true) AS def,
            ARRAY(SELECT DISTINCT r2.oid FROM pg_rewrite rw JOIN pg_depend d ON d.objid = rw.oid
                  JOIN pg_class r2 ON r2.oid = d.refobjid AND r2.relkind = 'v' AND r2.oid <> c.oid
                  WHERE rw.ev_class = c.oid) AS deps
     FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relkind = 'v'`
  );
  const done = new Set();
  while (done.size < views.length) {
    const ready = views.filter((v) => !done.has(v.oid) && v.deps.every((d) => done.has(d)));
    if (!ready.length) throw new Error("Views depend on each other in a cycle");
    for (const v of ready.sort((a, b) => a.relname.localeCompare(b.relname))) {
      out.push(`CREATE VIEW ${ident(v.relname)} AS\n${v.def.replace(/public\./g, "")}\n`);
      done.add(v.oid);
    }
  }

  const file = path.join(__dirname, "..", "schema.sql");
  fs.writeFileSync(file, out.join("\n") + "\n");
  console.log(
    `Wrote ${file}: ${tables.length} tables, ${sequences.length} sequences, ${constraints.length} constraints, ${indexes.length} indexes, ${views.length} views.`
  );
  await db.end();
})().catch(async (err) => {
  console.error(err);
  await db.end();
  process.exit(1);
});
