import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Input } from "./Input";
import { Button } from "./Button";
import { CheckBox } from "./CheckBox";
import { RatingBar } from "./RatingBar";
import { ReactTable } from "./ReactTable";
import { Modal } from "./Modal";
export { Img, Text, Heading, Input, Button, CheckBox, RatingBar, ReactTable, Modal };
