-- Generated by device/scripts/export-schema.js from the cloud database. Do not edit by hand.
-- 2026-10-01T20:51:50.336Z
-- cloud-migrations: 32

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

CREATE SEQUENCE admin_audit_log_id_seq AS bigint START 1 INCREMENT 1;
CREATE SEQUENCE announcements_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE bank_payment_intents_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE categories_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE contacts_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE login_events_id_seq AS bigint START 1 INCREMENT 1;
CREATE SEQUENCE lots_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE party_transactions_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE password_reset_requests_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE products_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE refunds_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE sale_transactions_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE sales_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE shift_cash_movements_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE shifts_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE shops_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE stock_adjustments_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE store_credit_redemptions_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE subscription_payments_id_seq AS integer START 1 INCREMENT 1;
CREATE SEQUENCE users_id_seq AS integer START 1 INCREMENT 1;

CREATE TABLE admin_audit_log (
  id bigint DEFAULT nextval('admin_audit_log_id_seq'::regclass) NOT NULL,
  admin_user_id integer,
  action text NOT NULL,
  shop_id integer,
  details jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE announcements (
  id integer DEFAULT nextval('announcements_id_seq'::regclass) NOT NULL,
  title text NOT NULL,
  body text DEFAULT ''::text NOT NULL,
  level text DEFAULT 'info'::text NOT NULL,
  shop_id integer,
  tier text,
  starts_at timestamp without time zone DEFAULT now() NOT NULL,
  ends_at timestamp without time zone,
  created_by integer,
  created_at timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE bank_payment_intents (
  id integer DEFAULT nextval('bank_payment_intents_id_seq'::regclass) NOT NULL,
  status text DEFAULT 'awaiting_payment'::text NOT NULL,
  cart_snapshot jsonb NOT NULL,
  amount numeric NOT NULL,
  voucher_code text,
  store_credit_redeemed numeric,
  created_by integer,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  resolved_by integer,
  resolved_at timestamp without time zone,
  resolution_note text,
  auto_confirmed boolean DEFAULT false NOT NULL,
  transaction_id integer,
  last_confirm_error text,
  qr_data_url text,
  matched_source_text text,
  match_candidates jsonb,
  channel text DEFAULT 'bank_transfer'::text NOT NULL,
  gateway_txn_ref text,
  gateway_response_code text,
  shop_id integer NOT NULL
);
CREATE TABLE categories (
  id integer DEFAULT nextval('categories_id_seq'::regclass) NOT NULL,
  category_name text NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE contacts (
  id integer DEFAULT nextval('contacts_id_seq'::regclass) NOT NULL,
  name text NOT NULL,
  is_customer boolean DEFAULT false NOT NULL,
  is_vendor boolean DEFAULT false NOT NULL,
  phone text,
  email text,
  address text,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE login_events (
  id bigint DEFAULT nextval('login_events_id_seq'::regclass) NOT NULL,
  username text NOT NULL,
  user_id integer,
  shop_id integer,
  outcome text NOT NULL,
  ip text,
  user_agent text,
  created_at timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE lot_sequences (
  vendor_id integer NOT NULL,
  product_id integer NOT NULL,
  last_number integer DEFAULT 0 NOT NULL,
  shop_id integer NOT NULL
);
CREATE TABLE lots (
  id integer DEFAULT nextval('lots_id_seq'::regclass) NOT NULL,
  product_id integer NOT NULL,
  vendor_id integer,
  lot_code text NOT NULL,
  buying_price numeric DEFAULT 0 NOT NULL,
  qty_received integer DEFAULT 0 NOT NULL,
  qty_remaining integer DEFAULT 0 NOT NULL,
  received_at timestamp without time zone DEFAULT now() NOT NULL,
  received_by integer,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE party_transactions (
  id integer DEFAULT nextval('party_transactions_id_seq'::regclass) NOT NULL,
  contact_id integer NOT NULL,
  direction text NOT NULL,
  kind text NOT NULL,
  amount numeric NOT NULL,
  occurred_on timestamp without time zone DEFAULT now() NOT NULL,
  note text,
  sale_id integer,
  lot_id integer,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE password_reset_requests (
  id integer DEFAULT nextval('password_reset_requests_id_seq'::regclass) NOT NULL,
  user_id integer NOT NULL,
  shop_id integer,
  claimed_cnic text,
  claimed_phone text,
  status text DEFAULT 'pending'::text NOT NULL,
  requested_at timestamp without time zone DEFAULT now() NOT NULL,
  resolved_by integer,
  resolved_at timestamp without time zone,
  notes text
);
CREATE TABLE platform_settings (
  key text NOT NULL,
  value text NOT NULL,
  updated_at timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE products (
  id integer DEFAULT nextval('products_id_seq'::regclass) NOT NULL,
  productname text NOT NULL,
  buyingprice numeric DEFAULT 0 NOT NULL,
  quantity integer DEFAULT 0 NOT NULL,
  category_id integer,
  batch_tracked boolean DEFAULT false NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE refunds (
  id integer DEFAULT nextval('refunds_id_seq'::regclass) NOT NULL,
  sale_id integer NOT NULL,
  transaction_id integer,
  quantity integer NOT NULL,
  refund_amount numeric NOT NULL,
  refund_method text NOT NULL,
  condition text DEFAULT 'resellable'::text NOT NULL,
  reason text NOT NULL,
  refunded_by integer,
  refunded_at timestamp without time zone DEFAULT now() NOT NULL,
  contact_id integer,
  shift_id integer,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL,
  receipt_no text NOT NULL
);
CREATE TABLE sale_transactions (
  id integer DEFAULT nextval('sale_transactions_id_seq'::regclass) NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  sold_by integer,
  payment_method text,
  contact_id integer,
  store_credit_applied numeric DEFAULT 0 NOT NULL,
  shift_id integer,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL,
  receipt_no text NOT NULL
);
CREATE TABLE sales (
  id integer DEFAULT nextval('sales_id_seq'::regclass) NOT NULL,
  selling_price numeric NOT NULL,
  quantity integer NOT NULL,
  product_id integer,
  sale_time timestamp without time zone DEFAULT now() NOT NULL,
  lot_id integer,
  buying_price numeric,
  sold_by integer,
  is_voided boolean DEFAULT false NOT NULL,
  voided_at timestamp without time zone,
  void_reason text,
  voided_by integer,
  transaction_id integer,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE settings (
  key text NOT NULL,
  value text NOT NULL,
  shop_id integer NOT NULL
);
CREATE TABLE shift_cash_movements (
  id integer DEFAULT nextval('shift_cash_movements_id_seq'::regclass) NOT NULL,
  shift_id integer NOT NULL,
  amount numeric NOT NULL,
  reason text NOT NULL,
  contact_id integer,
  recorded_by integer NOT NULL,
  recorded_at timestamp without time zone DEFAULT now() NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE shifts (
  id integer DEFAULT nextval('shifts_id_seq'::regclass) NOT NULL,
  opened_by integer NOT NULL,
  opened_at timestamp without time zone DEFAULT now() NOT NULL,
  opening_float numeric DEFAULT 0 NOT NULL,
  closed_by integer,
  closed_at timestamp without time zone,
  expected_cash numeric,
  counted_cash numeric,
  variance numeric,
  status text DEFAULT 'open'::text NOT NULL,
  notes text,
  last_activity_at timestamp without time zone DEFAULT now() NOT NULL,
  auto_closed boolean DEFAULT false NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE shop_egress_daily (
  shop_id integer NOT NULL,
  day date NOT NULL,
  bytes bigint DEFAULT 0 NOT NULL,
  request_count integer DEFAULT 0 NOT NULL
);
CREATE TABLE shops (
  id integer DEFAULT nextval('shops_id_seq'::regclass) NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  tier text DEFAULT 'basic'::text NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  max_users integer DEFAULT 5 NOT NULL,
  storage_quota_percent numeric,
  forwarder_secret_hash text,
  forwarder_secret_created_at timestamp without time zone,
  max_devices integer DEFAULT 1 NOT NULL
);
CREATE TABLE stock_adjustments (
  id integer DEFAULT nextval('stock_adjustments_id_seq'::regclass) NOT NULL,
  product_id integer NOT NULL,
  lot_id integer,
  quantity_change integer NOT NULL,
  buying_price numeric NOT NULL,
  reason_code text NOT NULL,
  note text,
  adjusted_by integer NOT NULL,
  adjusted_at timestamp without time zone DEFAULT now() NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE store_credit_redemptions (
  id integer DEFAULT nextval('store_credit_redemptions_id_seq'::regclass) NOT NULL,
  refund_id integer NOT NULL,
  amount numeric NOT NULL,
  transaction_id integer,
  redeemed_by integer,
  redeemed_at timestamp without time zone DEFAULT now() NOT NULL,
  shop_id integer NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);
CREATE TABLE subscription_payments (
  id integer DEFAULT nextval('subscription_payments_id_seq'::regclass) NOT NULL,
  shop_id integer NOT NULL,
  amount integer NOT NULL,
  method text NOT NULL,
  covers_from date NOT NULL,
  covers_until date NOT NULL,
  reference text,
  note text,
  recorded_by integer,
  created_at timestamp without time zone DEFAULT now() NOT NULL
);
CREATE TABLE users (
  id integer DEFAULT nextval('users_id_seq'::regclass) NOT NULL,
  username text NOT NULL,
  password_hash text NOT NULL,
  display_name text NOT NULL,
  role text DEFAULT 'cashier'::text NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  shop_id integer,
  email text,
  phone text,
  cnic text,
  must_change_password boolean DEFAULT false NOT NULL,
  uuid uuid DEFAULT gen_random_uuid() NOT NULL
);

ALTER TABLE admin_audit_log ADD CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id);
ALTER TABLE announcements ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_pkey PRIMARY KEY (id);
ALTER TABLE categories ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE contacts ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);
ALTER TABLE login_events ADD CONSTRAINT login_events_pkey PRIMARY KEY (id);
ALTER TABLE lot_sequences ADD CONSTRAINT lot_sequences_pkey PRIMARY KEY (shop_id, vendor_id, product_id);
ALTER TABLE lots ADD CONSTRAINT lots_pkey PRIMARY KEY (id);
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_pkey PRIMARY KEY (id);
ALTER TABLE password_reset_requests ADD CONSTRAINT password_reset_requests_pkey PRIMARY KEY (id);
ALTER TABLE platform_settings ADD CONSTRAINT platform_settings_pkey PRIMARY KEY (key);
ALTER TABLE products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE refunds ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);
ALTER TABLE sale_transactions ADD CONSTRAINT sale_transactions_pkey PRIMARY KEY (id);
ALTER TABLE sales ADD CONSTRAINT sales_pkey PRIMARY KEY (id);
ALTER TABLE settings ADD CONSTRAINT settings_pkey PRIMARY KEY (shop_id, key);
ALTER TABLE shift_cash_movements ADD CONSTRAINT shift_cash_movements_pkey PRIMARY KEY (id);
ALTER TABLE shifts ADD CONSTRAINT shifts_pkey PRIMARY KEY (id);
ALTER TABLE shop_egress_daily ADD CONSTRAINT shop_egress_daily_pkey PRIMARY KEY (shop_id, day);
ALTER TABLE shops ADD CONSTRAINT shops_pkey PRIMARY KEY (id);
ALTER TABLE stock_adjustments ADD CONSTRAINT stock_adjustments_pkey PRIMARY KEY (id);
ALTER TABLE store_credit_redemptions ADD CONSTRAINT store_credit_redemptions_pkey PRIMARY KEY (id);
ALTER TABLE subscription_payments ADD CONSTRAINT subscription_payments_pkey PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE categories ADD CONSTRAINT categories_shop_id_category_name_key UNIQUE (shop_id, category_name);
ALTER TABLE categories ADD CONSTRAINT categories_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE contacts ADD CONSTRAINT contacts_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE lots ADD CONSTRAINT lots_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE lots ADD CONSTRAINT lots_shop_id_lot_code_key UNIQUE (shop_id, lot_code);
ALTER TABLE products ADD CONSTRAINT products_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE products ADD CONSTRAINT products_shop_id_productname_key UNIQUE (shop_id, productname);
ALTER TABLE refunds ADD CONSTRAINT refunds_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE sale_transactions ADD CONSTRAINT sale_transactions_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE sales ADD CONSTRAINT sales_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE shifts ADD CONSTRAINT shifts_shop_id_id_key UNIQUE (shop_id, id);
ALTER TABLE shops ADD CONSTRAINT shops_slug_key UNIQUE (slug);
ALTER TABLE users ADD CONSTRAINT users_username_key UNIQUE (username);
ALTER TABLE announcements ADD CONSTRAINT announcements_level_check CHECK ((level = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])));
ALTER TABLE announcements ADD CONSTRAINT announcements_tier_check CHECK (((tier IS NULL) OR (tier = ANY (ARRAY['basic'::text, 'smart'::text, 'advanced'::text]))));
ALTER TABLE announcements ADD CONSTRAINT announcements_window_check CHECK (((ends_at IS NULL) OR (ends_at > starts_at)));
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_amount_positive CHECK ((amount > (0)::numeric));
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_channel_check CHECK ((channel = ANY (ARRAY['bank_transfer'::text, 'jazzcash'::text, 'easypaisa'::text])));
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_status_check CHECK ((status = ANY (ARRAY['awaiting_payment'::text, 'confirmed'::text, 'cancelled'::text, 'ambiguous'::text])));
ALTER TABLE login_events ADD CONSTRAINT login_events_outcome_check CHECK ((outcome = ANY (ARRAY['success'::text, 'failure'::text, 'locked'::text])));
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_amount_check CHECK ((((kind = ANY (ARRAY['charge'::text, 'payment'::text])) AND (amount > (0)::numeric)) OR ((kind = 'adjustment'::text) AND (amount <> (0)::numeric))));
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_direction_check CHECK ((direction = ANY (ARRAY['receivable'::text, 'payable'::text])));
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_kind_check CHECK ((kind = ANY (ARRAY['charge'::text, 'payment'::text, 'adjustment'::text])));
ALTER TABLE password_reset_requests ADD CONSTRAINT password_reset_requests_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])));
ALTER TABLE refunds ADD CONSTRAINT refunds_condition_check CHECK ((condition = ANY (ARRAY['resellable'::text, 'damaged'::text])));
ALTER TABLE refunds ADD CONSTRAINT refunds_method_check CHECK ((refund_method = ANY (ARRAY['cash'::text, 'card'::text, 'store_credit'::text])));
ALTER TABLE refunds ADD CONSTRAINT refunds_quantity_positive CHECK ((quantity > 0));
ALTER TABLE shift_cash_movements ADD CONSTRAINT shift_cash_movements_amount_check CHECK ((amount <> (0)::numeric));
ALTER TABLE shifts ADD CONSTRAINT shifts_status_check CHECK ((status = ANY (ARRAY['open'::text, 'closed'::text])));
ALTER TABLE shops ADD CONSTRAINT shops_max_devices_check CHECK ((max_devices >= 0));
ALTER TABLE shops ADD CONSTRAINT shops_max_users_positive CHECK ((max_users > 0));
ALTER TABLE shops ADD CONSTRAINT shops_storage_quota_percent_range CHECK (((storage_quota_percent IS NULL) OR ((storage_quota_percent > (0)::numeric) AND (storage_quota_percent <= (100)::numeric))));
ALTER TABLE shops ADD CONSTRAINT shops_tier_check CHECK ((tier = ANY (ARRAY['basic'::text, 'smart'::text, 'advanced'::text])));
ALTER TABLE stock_adjustments ADD CONSTRAINT stock_adjustments_quantity_check CHECK ((quantity_change <> 0));
ALTER TABLE stock_adjustments ADD CONSTRAINT stock_adjustments_reason_check CHECK ((reason_code = ANY (ARRAY['damaged'::text, 'expired'::text, 'theft'::text, 'count_correction'::text, 'restock'::text, 'other'::text])));
ALTER TABLE store_credit_redemptions ADD CONSTRAINT store_credit_redemptions_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE subscription_payments ADD CONSTRAINT subscription_payments_amount_check CHECK ((amount >= 0));
ALTER TABLE subscription_payments ADD CONSTRAINT subscription_payments_method_check CHECK ((method = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'jazzcash'::text, 'easypaisa'::text, 'card'::text, 'other'::text, 'trial'::text, 'waiver'::text])));
ALTER TABLE subscription_payments ADD CONSTRAINT subscription_payments_period_check CHECK ((covers_until > covers_from));
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'cashier'::text, 'superadmin'::text])));
ALTER TABLE users ADD CONSTRAINT users_superadmin_no_shop_check CHECK (((role = 'superadmin'::text) = (shop_id IS NULL)));
ALTER TABLE admin_audit_log ADD CONSTRAINT admin_audit_log_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES users(id);
ALTER TABLE admin_audit_log ADD CONSTRAINT admin_audit_log_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE announcements ADD CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE announcements ADD CONSTRAINT announcements_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_created_by_fkey FOREIGN KEY (created_by) REFERENCES users(id);
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES users(id);
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE bank_payment_intents ADD CONSTRAINT bank_payment_intents_transaction_id_same_shop_fkey FOREIGN KEY (shop_id, transaction_id) REFERENCES sale_transactions(shop_id, id);
ALTER TABLE categories ADD CONSTRAINT categories_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE contacts ADD CONSTRAINT contacts_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE login_events ADD CONSTRAINT login_events_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE login_events ADD CONSTRAINT login_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE lot_sequences ADD CONSTRAINT lot_sequences_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE lots ADD CONSTRAINT lots_product_id_same_shop_fkey FOREIGN KEY (shop_id, product_id) REFERENCES products(shop_id, id) ON DELETE CASCADE;
ALTER TABLE lots ADD CONSTRAINT lots_received_by_fkey FOREIGN KEY (received_by) REFERENCES users(id);
ALTER TABLE lots ADD CONSTRAINT lots_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE lots ADD CONSTRAINT lots_vendor_id_same_shop_fkey FOREIGN KEY (shop_id, vendor_id) REFERENCES contacts(shop_id, id);
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_contact_id_same_shop_fkey FOREIGN KEY (shop_id, contact_id) REFERENCES contacts(shop_id, id);
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_lot_id_same_shop_fkey FOREIGN KEY (shop_id, lot_id) REFERENCES lots(shop_id, id);
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_sale_id_same_shop_fkey FOREIGN KEY (shop_id, sale_id) REFERENCES sales(shop_id, id);
ALTER TABLE party_transactions ADD CONSTRAINT party_transactions_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE password_reset_requests ADD CONSTRAINT password_reset_requests_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES users(id);
ALTER TABLE password_reset_requests ADD CONSTRAINT password_reset_requests_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE password_reset_requests ADD CONSTRAINT password_reset_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE products ADD CONSTRAINT products_category_id_same_shop_fkey FOREIGN KEY (shop_id, category_id) REFERENCES categories(shop_id, id);
ALTER TABLE products ADD CONSTRAINT products_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE refunds ADD CONSTRAINT refunds_contact_id_same_shop_fkey FOREIGN KEY (shop_id, contact_id) REFERENCES contacts(shop_id, id);
ALTER TABLE refunds ADD CONSTRAINT refunds_refunded_by_fkey FOREIGN KEY (refunded_by) REFERENCES users(id);
ALTER TABLE refunds ADD CONSTRAINT refunds_sale_id_same_shop_fkey FOREIGN KEY (shop_id, sale_id) REFERENCES sales(shop_id, id);
ALTER TABLE refunds ADD CONSTRAINT refunds_shift_id_same_shop_fkey FOREIGN KEY (shop_id, shift_id) REFERENCES shifts(shop_id, id);
ALTER TABLE refunds ADD CONSTRAINT refunds_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE refunds ADD CONSTRAINT refunds_transaction_id_same_shop_fkey FOREIGN KEY (shop_id, transaction_id) REFERENCES sale_transactions(shop_id, id);
ALTER TABLE sale_transactions ADD CONSTRAINT sale_transactions_contact_id_same_shop_fkey FOREIGN KEY (shop_id, contact_id) REFERENCES contacts(shop_id, id);
ALTER TABLE sale_transactions ADD CONSTRAINT sale_transactions_shift_id_same_shop_fkey FOREIGN KEY (shop_id, shift_id) REFERENCES shifts(shop_id, id);
ALTER TABLE sale_transactions ADD CONSTRAINT sale_transactions_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE sale_transactions ADD CONSTRAINT sale_transactions_sold_by_fkey FOREIGN KEY (sold_by) REFERENCES users(id);
ALTER TABLE sales ADD CONSTRAINT sales_lot_id_same_shop_fkey FOREIGN KEY (shop_id, lot_id) REFERENCES lots(shop_id, id);
ALTER TABLE sales ADD CONSTRAINT sales_product_id_same_shop_fkey FOREIGN KEY (shop_id, product_id) REFERENCES products(shop_id, id);
ALTER TABLE sales ADD CONSTRAINT sales_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE sales ADD CONSTRAINT sales_sold_by_fkey FOREIGN KEY (sold_by) REFERENCES users(id);
ALTER TABLE sales ADD CONSTRAINT sales_transaction_id_same_shop_fkey FOREIGN KEY (shop_id, transaction_id) REFERENCES sale_transactions(shop_id, id);
ALTER TABLE sales ADD CONSTRAINT sales_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES users(id);
ALTER TABLE settings ADD CONSTRAINT settings_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE shift_cash_movements ADD CONSTRAINT shift_cash_movements_contact_id_same_shop_fkey FOREIGN KEY (shop_id, contact_id) REFERENCES contacts(shop_id, id);
ALTER TABLE shift_cash_movements ADD CONSTRAINT shift_cash_movements_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES users(id);
ALTER TABLE shift_cash_movements ADD CONSTRAINT shift_cash_movements_shift_id_same_shop_fkey FOREIGN KEY (shop_id, shift_id) REFERENCES shifts(shop_id, id);
ALTER TABLE shift_cash_movements ADD CONSTRAINT shift_cash_movements_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE shifts ADD CONSTRAINT shifts_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES users(id);
ALTER TABLE shifts ADD CONSTRAINT shifts_opened_by_fkey FOREIGN KEY (opened_by) REFERENCES users(id);
ALTER TABLE shifts ADD CONSTRAINT shifts_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE shop_egress_daily ADD CONSTRAINT shop_egress_daily_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE stock_adjustments ADD CONSTRAINT stock_adjustments_adjusted_by_fkey FOREIGN KEY (adjusted_by) REFERENCES users(id);
ALTER TABLE stock_adjustments ADD CONSTRAINT stock_adjustments_lot_id_same_shop_fkey FOREIGN KEY (shop_id, lot_id) REFERENCES lots(shop_id, id);
ALTER TABLE stock_adjustments ADD CONSTRAINT stock_adjustments_product_id_same_shop_fkey FOREIGN KEY (shop_id, product_id) REFERENCES products(shop_id, id);
ALTER TABLE stock_adjustments ADD CONSTRAINT stock_adjustments_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE store_credit_redemptions ADD CONSTRAINT store_credit_redemptions_redeemed_by_fkey FOREIGN KEY (redeemed_by) REFERENCES users(id);
ALTER TABLE store_credit_redemptions ADD CONSTRAINT store_credit_redemptions_refund_id_same_shop_fkey FOREIGN KEY (shop_id, refund_id) REFERENCES refunds(shop_id, id);
ALTER TABLE store_credit_redemptions ADD CONSTRAINT store_credit_redemptions_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE store_credit_redemptions ADD CONSTRAINT store_credit_redemptions_transaction_id_same_shop_fkey FOREIGN KEY (shop_id, transaction_id) REFERENCES sale_transactions(shop_id, id);
ALTER TABLE subscription_payments ADD CONSTRAINT subscription_payments_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES users(id);
ALTER TABLE subscription_payments ADD CONSTRAINT subscription_payments_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);
ALTER TABLE users ADD CONSTRAINT users_shop_id_fkey FOREIGN KEY (shop_id) REFERENCES shops(id);

ALTER SEQUENCE password_reset_requests_id_seq OWNED BY password_reset_requests.id;
ALTER SEQUENCE sales_id_seq OWNED BY sales.id;
ALTER SEQUENCE refunds_id_seq OWNED BY refunds.id;
ALTER SEQUENCE users_id_seq OWNED BY users.id;
ALTER SEQUENCE store_credit_redemptions_id_seq OWNED BY store_credit_redemptions.id;
ALTER SEQUENCE shifts_id_seq OWNED BY shifts.id;
ALTER SEQUENCE shift_cash_movements_id_seq OWNED BY shift_cash_movements.id;
ALTER SEQUENCE party_transactions_id_seq OWNED BY party_transactions.id;
ALTER SEQUENCE categories_id_seq OWNED BY categories.id;
ALTER SEQUENCE products_id_seq OWNED BY products.id;
ALTER SEQUENCE contacts_id_seq OWNED BY contacts.id;
ALTER SEQUENCE sale_transactions_id_seq OWNED BY sale_transactions.id;
ALTER SEQUENCE lots_id_seq OWNED BY lots.id;
ALTER SEQUENCE stock_adjustments_id_seq OWNED BY stock_adjustments.id;
ALTER SEQUENCE bank_payment_intents_id_seq OWNED BY bank_payment_intents.id;
ALTER SEQUENCE shops_id_seq OWNED BY shops.id;
ALTER SEQUENCE admin_audit_log_id_seq OWNED BY admin_audit_log.id;
ALTER SEQUENCE login_events_id_seq OWNED BY login_events.id;
ALTER SEQUENCE subscription_payments_id_seq OWNED BY subscription_payments.id;
ALTER SEQUENCE announcements_id_seq OWNED BY announcements.id;

CREATE INDEX idx_admin_audit_log_created ON admin_audit_log USING btree (created_at DESC);
CREATE INDEX idx_admin_audit_log_shop ON admin_audit_log USING btree (shop_id, created_at DESC);
CREATE INDEX idx_announcements_window ON announcements USING btree (starts_at, ends_at);
CREATE INDEX idx_bank_payment_intents_gateway_txn_ref ON bank_payment_intents USING btree (gateway_txn_ref);
CREATE INDEX idx_bank_payment_intents_shop_created_at ON bank_payment_intents USING btree (shop_id, created_at);
CREATE INDEX idx_bank_payment_intents_shop_status ON bank_payment_intents USING btree (shop_id, status);
CREATE INDEX idx_categories_shop_id ON categories USING btree (shop_id);
CREATE UNIQUE INDEX idx_categories_uuid ON categories USING btree (uuid);
CREATE INDEX idx_contacts_shop_customer_name ON contacts USING btree (shop_id, name) WHERE (is_customer = true);
CREATE INDEX idx_contacts_shop_vendor_name ON contacts USING btree (shop_id, name) WHERE (is_vendor = true);
CREATE UNIQUE INDEX idx_contacts_uuid ON contacts USING btree (uuid);
CREATE INDEX idx_login_events_created ON login_events USING btree (created_at DESC);
CREATE INDEX idx_login_events_ip ON login_events USING btree (ip, created_at DESC);
CREATE INDEX idx_login_events_shop ON login_events USING btree (shop_id, created_at DESC);
CREATE INDEX idx_login_events_user_success ON login_events USING btree (user_id, created_at DESC) WHERE (outcome = 'success'::text);
CREATE INDEX idx_login_events_username ON login_events USING btree (username, created_at DESC);
CREATE INDEX idx_lots_shop_code_trgm ON lots USING gin (shop_id, lot_code gin_trgm_ops);
CREATE INDEX idx_lots_shop_product_id ON lots USING btree (shop_id, product_id);
CREATE UNIQUE INDEX idx_lots_uuid ON lots USING btree (uuid);
CREATE INDEX idx_lots_vendor_id ON lots USING btree (vendor_id);
CREATE INDEX idx_party_transactions_sale_id ON party_transactions USING btree (sale_id);
CREATE INDEX idx_party_transactions_shop_contact_direction ON party_transactions USING btree (shop_id, contact_id, direction);
CREATE INDEX idx_party_transactions_shop_occurred_on ON party_transactions USING btree (shop_id, occurred_on);
CREATE UNIQUE INDEX idx_party_transactions_uuid ON party_transactions USING btree (uuid);
CREATE UNIQUE INDEX idx_password_reset_one_pending_per_user ON password_reset_requests USING btree (user_id) WHERE (status = 'pending'::text);
CREATE INDEX idx_password_reset_requests_status ON password_reset_requests USING btree (status);
CREATE INDEX idx_products_shop_category_id ON products USING btree (shop_id, category_id);
CREATE INDEX idx_products_shop_name_trgm ON products USING gin (shop_id, productname gin_trgm_ops);
CREATE UNIQUE INDEX idx_products_uuid ON products USING btree (uuid);
CREATE UNIQUE INDEX idx_refunds_receipt_no ON refunds USING btree (shop_id, receipt_no);
CREATE INDEX idx_refunds_sale_id ON refunds USING btree (sale_id);
CREATE INDEX idx_refunds_shift_id ON refunds USING btree (shift_id);
CREATE INDEX idx_refunds_shop_refunded_at ON refunds USING btree (shop_id, refunded_at);
CREATE INDEX idx_refunds_transaction_id ON refunds USING btree (transaction_id);
CREATE UNIQUE INDEX idx_refunds_uuid ON refunds USING btree (uuid);
CREATE UNIQUE INDEX idx_sale_transactions_receipt_no ON sale_transactions USING btree (shop_id, receipt_no);
CREATE INDEX idx_sale_transactions_shift_id ON sale_transactions USING btree (shift_id);
CREATE INDEX idx_sale_transactions_shop_id ON sale_transactions USING btree (shop_id);
CREATE UNIQUE INDEX idx_sale_transactions_uuid ON sale_transactions USING btree (uuid);
CREATE INDEX idx_sales_lot_id ON sales USING btree (lot_id);
CREATE INDEX idx_sales_shop_product_id ON sales USING btree (shop_id, product_id);
CREATE INDEX idx_sales_shop_sale_time ON sales USING btree (shop_id, sale_time);
CREATE INDEX idx_sales_shop_voided_at ON sales USING btree (shop_id, voided_at) WHERE is_voided;
CREATE UNIQUE INDEX idx_sales_uuid ON sales USING btree (uuid);
CREATE INDEX idx_shift_cash_movements_shift_id ON shift_cash_movements USING btree (shift_id);
CREATE INDEX idx_shift_cash_movements_shop_id ON shift_cash_movements USING btree (shop_id);
CREATE UNIQUE INDEX idx_shift_cash_movements_uuid ON shift_cash_movements USING btree (uuid);
CREATE UNIQUE INDEX idx_shifts_one_open_per_user ON shifts USING btree (opened_by) WHERE (status = 'open'::text);
CREATE INDEX idx_shifts_open_last_activity ON shifts USING btree (last_activity_at) WHERE (status = 'open'::text);
CREATE INDEX idx_shifts_shop_status ON shifts USING btree (shop_id, status);
CREATE UNIQUE INDEX idx_shifts_uuid ON shifts USING btree (uuid);
CREATE INDEX idx_shop_egress_daily_day ON shop_egress_daily USING btree (day);
CREATE UNIQUE INDEX idx_shops_forwarder_secret_hash ON shops USING btree (forwarder_secret_hash) WHERE (forwarder_secret_hash IS NOT NULL);
CREATE INDEX idx_stock_adjustments_shop_adjusted_at ON stock_adjustments USING btree (shop_id, adjusted_at);
CREATE INDEX idx_stock_adjustments_shop_product_id ON stock_adjustments USING btree (shop_id, product_id);
CREATE UNIQUE INDEX idx_stock_adjustments_uuid ON stock_adjustments USING btree (uuid);
CREATE INDEX idx_store_credit_redemptions_refund ON store_credit_redemptions USING btree (refund_id);
CREATE INDEX idx_store_credit_redemptions_shop_id ON store_credit_redemptions USING btree (shop_id);
CREATE INDEX idx_store_credit_redemptions_transaction ON store_credit_redemptions USING btree (transaction_id);
CREATE UNIQUE INDEX idx_store_credit_redemptions_uuid ON store_credit_redemptions USING btree (uuid);
CREATE INDEX idx_subscription_payments_shop ON subscription_payments USING btree (shop_id, covers_until DESC);
CREATE UNIQUE INDEX idx_users_cnic ON users USING btree (cnic) WHERE (cnic IS NOT NULL);
CREATE INDEX idx_users_shop_id ON users USING btree (shop_id);
CREATE UNIQUE INDEX idx_users_uuid ON users USING btree (uuid);

CREATE VIEW party_balances AS
 SELECT shop_id,
    contact_id,
    direction,
    sum(
        CASE
            WHEN kind = 'payment'::text THEN - amount
            ELSE amount
        END) AS balance,
    sum(
        CASE
            WHEN kind = 'charge'::text THEN amount
            ELSE 0::numeric
        END) AS total_charged,
    sum(
        CASE
            WHEN kind = 'payment'::text THEN amount
            ELSE 0::numeric
        END) AS total_paid,
    max(occurred_on) AS last_activity_on,
    count(*) AS transaction_count
   FROM party_transactions
  GROUP BY shop_id, contact_id, direction;

CREATE VIEW sales_ledger AS
 SELECT s.id AS sale_id,
    s.shop_id,
    s.product_id,
    s.sale_time AS event_time,
    s.quantity,
    s.selling_price,
    s.buying_price,
    s.transaction_id
   FROM sales s
  WHERE s.is_voided = false
UNION ALL
 SELECT r.sale_id,
    s.shop_id,
    s.product_id,
    r.refunded_at AS event_time,
    - r.quantity AS quantity,
    r.refund_amount / r.quantity::numeric AS selling_price,
    s.buying_price,
    s.transaction_id
   FROM refunds r
     JOIN sales s ON r.sale_id = s.id
  WHERE s.is_voided = false;

CREATE VIEW store_credit_voucher_balances AS
 SELECT r.id AS refund_id,
    r.shop_id,
    r.refund_amount AS initial_amount,
    r.contact_id,
    r.refunded_at,
    r.refund_amount - COALESCE(sum(red.amount), 0::numeric) AS balance
   FROM refunds r
     LEFT JOIN store_credit_redemptions red ON red.refund_id = r.id
  WHERE r.refund_method = 'store_credit'::text
  GROUP BY r.id, r.shop_id;

